version: '3'
services:
  backend:
    build:
      context: ./ProjetLaboBack  # Chemin vers le Dockerfile du back-end
    container_name: backend-labo-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./ProjetLaboFront  # Chemin vers le Dockerfile du front-end
    container_name: frontend-labo-app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
