version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: labo_db
      POSTGRES_USER: imane
      POSTGRES_PASSWORD: 123
    ports:  # Corrigé ici
      - "8084:5432"
    networks:
      - app-network
  backend:
    build:
      context: ./ProjetLaboBack  # Chemin vers le Dockerfile du back-end
    container_name: backend-labo-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build:
      context: ./project-labo-front # Chemin vers le Dockerfile du front-end
    container_name: frontend-labo-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
