pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/UserImaneEl/ProjetLabo.git'
            }
        }


        stage('Build') {
            steps {
                bat 'mvn clean install' // Changer sh par bat
            }
        }

        stage('Package') {
            steps {
                bat 'mvn package' // Changer sh par bat
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t mon-app-springboot:latest .' // Changer sh par bat
            }
        }

        stage('Deploy Docker Container') {
            steps {
                bat 'docker run -d --name springboot-app -p 8080:8080 mon-app-springboot:latest' // Changer sh par bat
            }
        }
    }

    post {
        success {
            echo 'Le build et le déploiement ont réussi !'
        }
        failure {
            echo 'Échec du build ou du déploiement.'
        }
    }
}
